### PR TITLE
feat: add Ruff linter configuration to pyproject.toml

### PR DESCRIPTION
**Pull request by pg56714**
### Introduce Ruff Linter and Formatter

This PR integrates [Ruff](https://github.com/charliermarsh/ruff), a high-performance Python linter and formatter, into the project to enhance code quality and enforce consistent styling and standards.

- **Key features:**
  - High performance, handling large codebases with ease.
  - Broad compatibility with over 500 linting rules, supporting checks from tools like `pyflakes`, `pycodestyle`, and `mccabe`.
  - Autofix support for common issues (e.g., unused imports, outdated syntax).
  - Integrated with `pre-commit` for automatic linting before every commit.

- **How to use:**
  - Run `ruff check` to lint the codebase.
  - Run `ruff format` to format Python files according to project styling guidelines.

Ruff configuration is handled in `pyproject.toml`, making it easy to customize and manage.

image

image

image

Optimize the code after the future PR is approved.

### CODE REVIEW

**Comment by eucyt** [comment]
@pg56714 

Thank you so much for your contribution.

The line-bot-sdk-python project primarily generates a large portion of its code from OpenAPI. Therefore, it's not always guaranteed that the auto-generated code will be no lint warning (for example, it might contain unused variables). Additionally, since our team would need to maintain Ruff ourselves, we should consider this carefully.

One potential way to incorporate this would be to configure CI to warn about only missing imports. Specifically, this could involve:
- Setting it up to only warn about missing import statements.
- Using GitHub Actions for warnings instead of pre-commit.

Would it be possible to implement it this way?

**Comment by pg56714** [comment]
@eucyt
Thank you for your detailed feedback!
I have an idea—would it be more efficient to handle these warnings during the pre-commit stage? This way, we can resolve issues before pushing the code, reducing the time and resources needed for CI.

If you think this approach is feasible, I can try implementing it in this way or make adjustments based on your further suggestions.

**Comment by eucyt** [comment]
@pg56714 
I'm so sorry for the delayed response, and thank you for your prompt action.

Regarding the settings, I would like you to configure [F821](https://docs.astral.sh/ruff/rules/undefined-name/) instead of [F401](https://docs.astral.sh/ruff/rules/unused-import/). F401 checks for unused imports, which is unnecessary for auto-generated code. However, variables without imports can potentially cause bugs, so we need to be inspected. Additionally, I would like to disable auto-fix, as it generates many differences in the auto-generated files. We want to detect only errors that could be potential bug sources.

Furthermore, I would prefer to set up CI instead of pre-commit. Developers can disable pre-commit and commit changes regardless. In contrast, CI allows us to ensure checks are performed, making it more reliable.

**Comment by pg56714** [comment]
#709 Add the issues detected during the CI check to the description of #709.

**Comment by eucyt** [comment]
@pg56714 

Thank you for implementing the CI and sharing the details of the errors that occurred. I appreciate your detailed description.

Judging by the nature of these errors, there should be no issue with actual usage. Please refer to this comment for more details. https://github.com/line/line-bot-sdk-python/issues/709#issuecomment-2519442976

Therefore, it doesn't seem so useful to inspect the files automatically generated by OpenAPI with ruff. I'm sorry for any inconvenience despite your efforts in implementation and investigation.

**Comment by pg56714** [comment]
Got it, and thank you for your explanation.

**Pull request closed without merging**
