### PR TITLE
Async-support-fastapi-sample

### PR DESCRIPTION
**Pull request by Wasdee**
create for #340 to add fastapi sample

### CODE REVIEW

**Review by shayeldossri — APPROVED** [review]

**Review by shayeldossri — CHANGES_REQUESTED** [review]
Closed

**Comment by CircleOnCircles** [comment]
> Some files (i.e. aiohttp_async_http_client.py, async_api.py) are already committed in #340?

I reset and add changes on top of master.

**Comment by CircleOnCircles** [comment]
could you add this as a part of hacktoberfest. [more info here](https://hacktoberfest.digitalocean.com/resources/maintainers)

**Review by louis70109 — APPROVED** [review]
LGTM

**Comment by i-Ching** [comment]
I replace aiohttp.ClientSession() with httpx.AsyncClient(), it works.
Hence I don't need import aiohttp under FastAPI or starlette environment.

import httpx
session = httpx.AsyncClient()
async_http_client = AiohttpAsyncHttpClient(session)
...

**Pull request merged**
