### PR TITLE
Add new API for Image Carousel

### PR DESCRIPTION
**Pull request by nnsnodnb**
https://devdocs.line.me/en/#image-carousel

### CODE REVIEW

**Comment by okdtsk** [comment]
Thank you for your contribution!

The `action` field of image carousel template is not list but just json object unlike CarouselTemplate.
Could you fix your implementation of `ImageCarouselColumn` and its test?

* Example json item of `columns` for image carousel template
```json
{
    "imageUrl": "https://example.com/bot/images/item1.jpg",
    "action": {
    "type": "postback",
    "label": "Buy",
    "data": "action=buy&itemid=111"
  }
}
```

**Comment by nnsnodnb** [comment]
Oh, sorry ;(
It is being revised now.

**Comment by okdtsk** [comment]
Thanks for your updates! :octocat:

I suggest not to separate postback action for standard templates and for image carousel because there is no difference except for the length of label value and our implementation has no validation process to check its length so we can use existing `PostbackTemplateAction` for image carousel.
Additionally it is better that each action/event has single corresponding class to reduce future maintenance cost of this sdk IMO.

https://devdocs.line.me/en/#template-message

Instead of new implementation of postback action for image carousel, how about modify docstring of existing `***TemplateAction`?

**Comment by bheghenkz** [comment]
bisa tolong buatkan saya bot. anti kicker

**Comment by nnsnodnb** [comment]
@okdtsk 
Sorry...
I fixed it to implementation in `PostbackTemplateAction` .
I actually implemented it in the application and confirmed the expected behavior.
Remove `ImagePostbackTemplateAction` .

**Comment by okdtsk** [comment]
@nnsnodnb 
Thank you, LGTM :octocat:  I'll merge this pr.

@bheghenkz 
If you have a general question of line bot, please ask in https://github.com/line/line-bot-faq. That repository is for general usage of line bot and separate from each sdk repo due to separation of concerns.

**Pull request merged**
