### PR TITLE
fix aiohttp error handling

### PR DESCRIPTION
**Pull request by yoshiya0503**
The highlights of this PR is follows.

https://github.com/line/line-bot-sdk-python/compare/master...yoshiya0503:master#diff-9aca243eb8cba00a4aa078ab3c6df50cae9e165cb4c3779a6114c90f5c61b3acR1650

BUT, I found the document

```
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#  *** DO NOT EDIT THIS FILE ***
#
#  1) Modify linebot/api.py
#  2) Run `python setup.py codegen`
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Maybe, this source was generated by some tools. If we want to use that tool, we should fix error handling process of 'api.py'.

### CODE REVIEW

**Comment by louis70109** [comment]
It's ok. Thanks for your contribution :)

**Comment by yoshiya0503** [comment]
fmfm 

https://github.com/line/line-bot-sdk-python/pull/364/files#diff-9aca243eb8cba00a4aa078ab3c6df50cae9e165cb4c3779a6114c90f5c61b3acR497

There are some remains to fix, however this fix is not so bad.

Plz wait a minutes, I will be able to fix this issue.

**Comment by yoshiya0503** [comment]
I finished to fix this issue.

I checked behavior of async/await error handling, and json response.

At a glance, there are no problems. it looks good to me.

Plz merge this PR :) (if different issue was happened, at least it gets pretty good.)

@louis70109

**Comment by louis70109** [comment]
@yoshiya0503 so appreciate your contribution, but could you add a few test cases about these changes? (Not all but need example for future PR~)

**Comment by yoshiya0503** [comment]
OK ! wait a minute. I'll be add the some test cases, when I have a time. (weekend work)

**Comment by yoshiya0503** [comment]
https://github.com/line/line-bot-sdk-python/pull/364/commits/fae733db48f497b7cef47dafa5b439d179d192ce

I add some test case for async HTTP client. but not exception case.

**Comment by yoshiya0503** [comment]
@louis70109 completed!! 

plz, review the test case.

**Review by louis70109 — APPROVED** [review]
LGTM !

**Pull request merged**
