### PR TITLE
Use OpenAPI generator

### PR DESCRIPTION
**Pull request by Yang-33**
This pull request replaces all clients and models in line-bot-sdk-python with new ones generated by OpenApi generator.

1. generator is based on [`PythonNextgenClientCodegen.java`](https://github.com/OpenAPITools/openapi-generator/blob/b26b6ac1a25525ab4125eb4e0a8f81a2c3d5c76b/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonNextgenClientCodegen.java) in https://github.com/OpenAPITools/openapi-generator. This pull request modifies it to customize `discriminator`'s behavior.
2. This pull request deletes old documents since it's no longer maintained yet. 
3. Samples and tests are updated. Everyone can look at usage of the latest sdk and test it.

There are some remaining tasks, but it's sufficient to replace because we easily update sdk more quickly than before, thanks to [line-openapi](https://github.com/line/line-openapi) and open api generator.
- Unknown json are not serialized to object because there is no fallback except for webhook event. though [line-bot-sdk-java](https://github.com/line/line-bot-sdk-java/tree/7b4743d9b41718325ba3b0406ad7ad7deb65c66a/line-bot-webhook/src/main/java/com/linecorp/bot/webhook/model) has it...
- there is no useful documentation in this repository. Some generated document can help developers, but it's not perfect. We should improve it after this change.

resolve https://github.com/line/line-bot-sdk-python/issues/431

### CODE REVIEW

**Comment by tokuhirom** [comment]
@louis70109 could you review this?

**Comment by louis70109** [comment]
@tokuhirom ok, let me check~

**Review by tokuhirom — APPROVED** [review]
LGTM~

**Review by louis70109 — APPROVED** [review]

**Comment by Yang-33** [comment]
Thank you for reviewing this change, @tokuhirom  @louis70109 !
I'll create short migration guide in the next release note.

**Pull request merged**
