### PR TITLE
ChannelAccessToken client doesn't have to require channel access token

### PR DESCRIPTION
**Pull request by Yang-33**

### CODE REVIEW

**Comment by Yang-33** [comment]
(I should replace mustache with pebble...)

**Review by tokuhirom — CHANGES_REQUESTED** [review]
Thank you, I think that's good.
However, I've started to feel that there might be a problem with the OpenAPI definition at the 'module_attach' part.

Only for the 'Attach by operation of the module channel provider', it should be possible to specify Authorization: Basic {base64({Channel ID}:{Channel Secret})}. For other APIs, they should be defined with Authorization Bearer.

But it's not being done that way now. The definition is wrong. The python sdk, unlike other SDKs, is looking at 'isBasicBearer', causing all APIs, including 'Attach by operation of the module channel provider', to become unusable. Because this makes all APIs unusable, I thought it would be better to not look at 'isBasicBearer' for now and merge it first, and then fix the openapi definition.

**Comment by tokuhirom** [comment]
ah, no. i misunderstood. module-attach.yml only contains the endpoint of the `Attach by operation of the module channel provider`.

**Comment by tokuhirom** [comment]
Maybe something like this is even better.

```
        self.default_headers['Authorization'] = '{% if isBasicBearer %}Basic{% else %}Bearer{% endif %} ' + configuration.access_token
```

**Comment by Yang-33** [comment]
Thank you for your comment! As you said, I forgot module-attach uses Basic Authentication. I fixed this in https://github.com/line/line-bot-sdk-python/pull/557/files/30f803f7e0d89cb623b0453dd7778e55eb8cc54f..b6cc1aac82143e761c3c03f2b60435044a51a28a. PTAL again!

**Review by tokuhirom — APPROVED** [review]

**Pull request merged**
