### PR TITLE
Support get bot info

### PR DESCRIPTION
**Pull request by CA-Lee**
Implemented following feature mentioned in #298 .

- Get bot info

Willing to receive any suggestion. If you please, label this PR as `hacktoberfest-accepted` , thanks.

### CODE REVIEW

**Comment by louis70109** [comment]
LGTM, 
@cryeo -san and @okue -san please check this.

**Comment by CA-Lee** [comment]
> Can you add get_bot_info() in document?

Sorry, I'm not clear about the documentation structure. Do I only need to modify the README.rst?

**Comment by louis70109** [comment]
> Sorry, I'm not clear about the documentation structure. Do I only need to modify the README.rst?

Yes~

**Review by louis70109 — APPROVED** [review]
LGTM

**Pull request merged**
